export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  ANALYTICS: '/analytics',
  MEDICATIONS: '/medications',
  SERVICES: '/services',
  ALERTS: '/alerts',
  IMPORTS: '/imports',
  ASSISTANT: '/assistant',
  SETTINGS: '/settings',
  PATIENTS: '/patients',
  ADMISSIONS: '/admissions',
  TRIAGES: '/triages',
  SERVICE_RECORDS: '/service-records',
  SURGERY_SCHEDULES: '/surgery-schedules',
  PROCEDURES: '/procedures',
  USERS: '/users',
  ROLES: '/roles',
} as const
